MODEL:
  DEVICE: "cpu"
  NUM_WORKERS: 5
  BATCH_SIZE: 5
  NUM_JOINTS: 21
  HOURGLASS:
    NUM_STAGES: 2
    NUM_MODULES: 2
    NUM_FEAT_CHANNELS: 256
  PRETRAIN_WEIGHT:
    HM_NET_PATH: "./model/pretrained_models/net_hm.pth"
    MESH_NET_PATH: "./model/pretrained_models/net_feat_mesh.pth"
    POSE_NET_PATH: "./model/pretrained_models/net_mesh_pose.pth"
GRAPH:
  TEMPLATE_PATH: "./data/hand_model.obj"
EVAL:
  SAVE_DIR: "./output"
  SAVE_BATCH_IMAGES_PRED: True
  PRINT_FREQ: 1
  SAVE_POSE_ESTIMATION: True
